on:
  push:
  schedule:
    - cron: '12 7 * * 1/3'

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Build/Push Docker
    steps:
    - name: Get latest release
      run: |
        echo "Trying to setup release variable"

        export TMPREL=$(curl -s https://api.github.com/repos/grafana/grafana/releases/latest | grep -Po '"tag_name": ".*"' | sed -E 's/"tag_name": "(.*)"/\1/g' | sed 's/\n//g')

        echo "RELEASE=$TMPREL" >> $GITHUB_ENV
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: repo
        repository: grafana/grafana
        ref: ${{ env.RELEASE }}
    - name: Docker login
      run: |
        echo "${{ secrets.HUB_PASS }}" | docker login --username "${{ secrets.HUB_USER }}" --password-stdin
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
    - name: inspect
      run: |
        docker buildx inspect --bootstrap
    - name: Build
      run: |
        cd repo
        cd packaging/docker/custom
        ls
        docker buildx build \
          --progress=plain \
          --pull \
          --build-arg GRAFANA_VERSION=master \
          --build-arg GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource \
          --platform  linux/amd64,linux/arm64,linux/arm/v7 \
          --output "type=image,push=true" \
          --tag betashil/grafana:latest \
          --file Dockerfile .
