on:
  push:
  schedule:
    - cron: '12 7 * * 1/3'

jobs: 
  build_docker:
    runs-on: ubuntu-latest
    name: Build/Push Docker
    steps:
    - name: Get latest release
      run: |
        export RELEASE=$(curl -s https://api.github.com/repos/grafana/grafana/releases/latest | grep -Po '"tag_name": ".*"' | sed -E 's/"tag_name": "(.*)"/\1/g' | sed 's/\n//g')
        echo $RELEASE
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: repo
        repository: grafana/grafana
        ref: $RELEASE
    - name: verbose
      run: |
        docker -v
        export DOCKER_CLI_EXPERIMENTAL=enabled
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Docker login
      run: |
        echo "${{ secrets.HUB_PASS }}" | docker login --username "${{ secrets.HUB_USER }}" --password-stdin
    - name: Build
      run: |
        cd repo
        # git checkout $(curl -s GET https://api.github.com/repos/grafana/grafana/releases/latest | grep -Po '"tag_name": ".*"' | sed -E 's/"tag_name": "(.*)"/\1/g' | sed 's/\n//g')
        cd packaging/docker/custom
        ls

        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        docker buildx create --use --driver docker-container

        docker buildx build \
          --progress=plain \
          --pull \
          --build-arg GRAFANA_VERSION=master \
          --build-arg GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource \
          --platform  linux/amd64,linux/arm64,linux/arm/v7 \
          --output "type=image,push=true" \
          --tag betashil/grafana:latest \
          --file Dockerfile .
