on:
  push:
    paths:
      - '.github/workflows/renderer.yml'
  schedule:
    - cron: '12 7 * * 5'

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Build/Push Docker
    steps:
    - name: Set Environment Variables
      run: |
        export RELEASE=$(curl -s https://api.github.com/repos/grafana/grafana-image-renderer/releases/latest | grep -Po '"tag_name": ".*"' | sed -E 's/"tag_name": "(.*)"/\1/g' | sed 's/\n//g')
        echo "RELEASE=$RELEASE" >> $GITHUB_ENV
        echo "PLATFORM=linux/amd64,linux/arm64,linux/arm/v7" >> $GITHUB_ENV
        echo "DOCKERHUB_SLUG=$(echo ${{ secrets.HUB_USER }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        repository: grafana/grafana-image-renderer
        ref: ${{ env.RELEASE }}
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_PASS }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        platforms: ${{ env.PLATFORM }}
        push: true
        tags: |
            ${{ env.DOCKERHUB_SLUG }}/grafana-image-renderer:latest
